/**
 * US Booths API — Base de datos de rutas
 * Origen: routes/api/admin.php, routes/api/client.php, routes/api/public.php, routes/api/webhooks.php
 * Modifica este archivo para actualizar la documentación automáticamente.
 */
window.API_ROUTES = {
  baseUrl: '/api',
  sources: [
    'routes/api/admin.php',
    'routes/api/client.php',
    'routes/api/public.php',
    'routes/api/webhooks.php'
  ],
  sections: [
    {
      id: 'admin-auth',
      title: 'Auth / usuario',
      subtitle: 'Base: /api (sin prefijo /api/admin para user-profile y logout)',
      badge: 'auth',
      routes: [
        { method: 'GET', path: '/api/user-profile', action: 'AuthController@userProfile' },
        { method: 'POST', path: '/api/logout', action: 'AuthController@logout' },
        { method: 'PUT', path: '/api/user/sidebar-width', action: 'AuthController@updateSidebarWidth' }
      ]
    },
    {
      id: 'admin-endpoints',
      title: 'Admin (prefijo /api/admin)',
      badge: 'auth',
      routes: [
        { method: 'GET', path: '/api/admin/email-templates', action: 'index' },
        { method: 'GET', path: '/api/admin/email-templates/{emailTemplate}', action: 'show' },
        { method: 'PUT', path: '/api/admin/email-templates/{emailTemplate}', action: 'update' },
        { method: 'GET', path: '/api/admin/email-templates/{emailTemplate}/users', action: 'getUsers' },
        { method: 'PUT', path: '/api/admin/email-templates/{emailTemplate}/users', action: 'updateUsers' },
        { method: 'PUT', path: '/api/admin/email-templates/{emailTemplate}/users/{personId}', action: 'updateUser' },
        { method: 'POST', path: '/api/admin/send-notification', action: 'PushNotificationController@sendNotification' },
        { method: 'POST', path: '/api/admin/register-device-token', action: 'store' },
        { method: 'GET', path: '/api/admin/dashboard', action: 'getDashboardData' },
        { method: 'DELETE', path: '/api/admin/user/{id}', action: 'UserController@destroy' },
        { method: 'GET', path: '/api/admin/user/info/{id}', action: 'getUserInfo' },
        { method: 'GET', path: '/api/admin/admins', action: 'index' },
        { method: 'POST', path: '/api/admin/admin', action: 'store' },
        { method: 'POST', path: '/api/admin/admins/bulk-destroy', action: 'bulkDestroy' },
        { method: 'GET', path: '/api/admin/admin/{id}', action: 'show' },
        { method: 'PUT', path: '/api/admin/admin/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/admin/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/admin/info/{id}', action: 'getUserInfo' },
        { method: 'GET', path: '/api/admin/admins/active/{id}', action: 'getActiveAdmins' },
        { method: 'GET', path: '/api/admin/admins/active-to-tasks/{id}', action: 'getActiveAdminsToTasks' },
        { method: 'POST', path: '/api/admin/update-profile-img', action: 'updateImageProfile' },
        { method: 'GET', path: '/api/admin/get-work-orders-completed/{id}', action: 'getWorkOrdersCompleted' },
        { method: 'POST', path: '/api/admin/pay-worked-hours', action: 'payToEmployee' },
        { method: 'PUT', path: '/api/admin/update-payment-worked-hours/{id}', action: 'updatePaymentEmployee' },
        { method: 'DELETE', path: '/api/admin/person-payment/{personPayment}', action: 'deletePayment' },
        { method: 'POST', path: '/api/admin/create-bill', action: 'createBill' },
        { method: 'GET', path: '/api/admin/contacts', action: 'index' },
        { method: 'POST', path: '/api/admin/client', action: 'store' },
        { method: 'GET', path: '/api/admin/client/{id}', action: 'show' },
        { method: 'PUT', path: '/api/admin/client/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/client/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/contacts/bulk-destroy', action: 'bulkDestroy' },
        { method: 'GET', path: '/api/admin/contacts/active', action: 'getActiveContacts' },
        { method: 'GET', path: '/api/admin/contacts/active-us-booths-connect', action: 'getActiveUsBoothsConnect' },
        { method: 'GET', path: '/api/admin/contacts-new-order', action: 'getContactsNewOrder' },
        { method: 'GET', path: '/api/admin/companies-contact', action: 'getCompaniesContact' },
        { method: 'GET', path: '/api/admin/get-projects-manager/{id}', action: 'getProjectsManager' },
        { method: 'GET', path: '/api/admin/workstations', action: 'index' },
        { method: 'POST', path: '/api/admin/workstation', action: 'store' },
        { method: 'GET', path: '/api/admin/workstation/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/workstation/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/workstation/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/workstations/active', action: 'getActiveWorkstation' },
        { method: 'GET', path: '/api/admin/get-workstations-factories', action: 'getWorkstationsFactories' },
        { method: 'GET', path: '/api/admin/roles', action: 'index' },
        { method: 'POST', path: '/api/admin/role', action: 'store' },
        { method: 'POST', path: '/api/admin/role/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/role/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/roles/active', action: 'getActiveRole' },
        { method: 'POST', path: '/api/admin/roles/permissions', action: 'updateRolePermissions' },
        { method: 'GET', path: '/api/admin/roles/module-permissions', action: 'getModulePermissions' },
        { method: 'GET', path: '/api/admin/roles/all-permissions', action: 'getAllPermissions' },
        { method: 'POST', path: '/api/admin/product/images', action: 'store' },
        { method: 'DELETE', path: '/api/admin/product/image/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/product/images/{id}', action: 'getProductImages' },
        { method: 'GET', path: '/api/admin/store-products', action: 'index' },
        { method: 'POST', path: '/api/admin/store-product', action: 'store' },
        { method: 'GET', path: '/api/admin/store-product/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/store-product/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/store-product/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/custom-products', action: 'index' },
        { method: 'POST', path: '/api/admin/custom-product', action: 'store' },
        { method: 'GET', path: '/api/admin/custom-product/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/custom-product/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/custom-product/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/all-custom-products', action: 'getAllCustomProducts' },
        { method: 'GET', path: '/api/admin/standard-products', action: 'index' },
        { method: 'POST', path: '/api/admin/standard-product', action: 'store' },
        { method: 'GET', path: '/api/admin/standard-product/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/standard-product/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/standard-product/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/get-standard-products', action: 'getStandardProducts' },
        { method: 'GET', path: '/api/admin/inventory', action: 'index' },
        { method: 'GET', path: '/api/admin/inventory/active/{id}', action: 'getActiveColors' },
        { method: 'POST', path: '/api/admin/inventory', action: 'store' },
        { method: 'GET', path: '/api/admin/inventory/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/inventory/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/inventory/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/inventory/bulk-destroy', action: 'bulkDestroy' },
        { method: 'POST', path: '/api/admin/update-image-material', action: 'updateImage' },
        { method: 'POST', path: '/api/admin/material-warehouse-in', action: 'materialIn' },
        { method: 'POST', path: '/api/admin/material-warehouse-out', action: 'materialOut' },
        { method: 'GET', path: '/api/admin/vendors', action: 'index' },
        { method: 'GET', path: '/api/admin/vendor/{id}', action: 'show' },
        { method: 'GET', path: '/api/admin/vendors/active/{workstationId}', action: 'getActiveVendors' },
        { method: 'POST', path: '/api/admin/vendor', action: 'store' },
        { method: 'POST', path: '/api/admin/vendor/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/vendor/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/vendors/bulk-delete', action: 'bulkDelete' },
        { method: 'GET', path: '/api/admin/vendor/{vendorId}/comments', action: 'getVendorComments' },
        { method: 'POST', path: '/api/admin/vendor-comment', action: 'store' },
        { method: 'PUT', path: '/api/admin/vendor-comment/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/vendor-comment/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/orders', action: 'index' },
        { method: 'GET', path: '/api/admin/order/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/order/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/order/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/orders/bulk-delete', action: 'bulkDelete' },
        { method: 'GET', path: '/api/admin/orders/active/{id}', action: 'getOrders' },
        { method: 'GET', path: '/api/admin/orders/contact', action: 'getContactOrders' },
        { method: 'GET', path: '/api/admin/orders/admin', action: 'getAdminOrders' },
        { method: 'GET', path: '/api/admin/archived-orders', action: 'getArchivedOrders' },
        { method: 'PUT', path: '/api/admin/order/deadline/{orderId}', action: 'updateDeadline' },
        { method: 'GET', path: '/api/admin/get-order-files/{id}', action: 'getOrderFiles' },
        { method: 'POST', path: '/api/admin/save-order-files', action: 'saveOrderFiles' },
        { method: 'DELETE', path: '/api/admin/delete-order-file/{id}', action: 'deleteOrderFile' },
        { method: 'POST', path: '/api/admin/send-quote', action: 'sendQuote' },
        { method: 'POST', path: '/api/admin/send-invoice', action: 'sendInvoice' },
        { method: 'POST', path: '/api/admin/send-receipt', action: 'sendReceipt' },
        { method: 'GET', path: '/api/admin/get-admins-to-assign/{id}', action: 'getAdminsToAssign' },
        { method: 'GET', path: '/api/admin/get-order-assigned/{id}', action: 'getOrderAssigned' },
        { method: 'POST', path: '/api/admin/manage-assigned-order', action: 'assignUserToOrder' },
        { method: 'GET', path: '/api/admin/get-files-qirp/{id}', action: 'getFilesQIRP' },
        { method: 'POST', path: '/api/admin/update-order', action: 'updateOrder' },
        { method: 'POST', path: '/api/admin/save-product-to-order', action: 'saveProductToOrder' },
        { method: 'POST', path: '/api/admin/assign-factory-to-order', action: 'assignFactory' },
        { method: 'GET', path: '/api/admin/order-comments/{id}', action: 'getOrderComments' },
        { method: 'POST', path: '/api/admin/order-comment', action: 'saveOrderComments' },
        { method: 'POST', path: '/api/admin/order-comment/{id}', action: 'updateOrderComments' },
        { method: 'DELETE', path: '/api/admin/order-comment-file/{id}', action: 'deleteOrderCommentFile' },
        { method: 'POST', path: '/api/admin/update-order-status', action: 'handleUpdateOrderStatus' },
        { method: 'POST', path: '/api/admin/send-order-advance/{id}', action: 'sendOrderAdvances' },
        { method: 'POST', path: '/api/admin/send-invoice-update-design', action: 'sendInvoiceAndUpdateToDesign' },
        { method: 'POST', path: '/api/admin/process-manual-payment', action: 'processManualPayment' },
        { method: 'POST', path: '/api/admin/duplicate-order', action: 'duplicateOrder' },
        { method: 'POST', path: '/api/admin/send-proposal', action: 'sendProposal' },
        { method: 'POST', path: '/api/admin/save-proposal', action: 'saveProposal' },
        { method: 'POST', path: '/api/admin/delete-proposal', action: 'deleteProposal' },
        { method: 'PUT', path: '/api/admin/confirm-proposal', action: 'confirmProposal' },
        { method: 'GET', path: '/api/admin/get-temp-order-items', action: 'getItems' },
        { method: 'POST', path: '/api/admin/save-add-temp-order-item', action: 'saveAddItem' },
        { method: 'POST', path: '/api/admin/edit-temp-order-item', action: 'editItem' },
        { method: 'POST', path: '/api/admin/add-temp-order-item', action: 'addItem' },
        { method: 'POST', path: '/api/admin/add-standard-temp-order-item', action: 'addStandardItem' },
        { method: 'DELETE', path: '/api/admin/delete-temp-order-item/{id}', action: 'deleteItem' },
        { method: 'DELETE', path: '/api/admin/cancel-temp-order-detail', action: 'deleteAllItems' },
        { method: 'POST', path: '/api/admin/process-order', action: 'processOrder' },
        { method: 'POST', path: '/api/admin/generate-pdf-quote/{id}', action: 'generatePdfQuote' },
        { method: 'GET', path: '/api/admin/send-pdf-quote/{id}', action: 'sendPdfQuote' },
        { method: 'GET', path: '/api/admin/generate-qr/{id}', action: 'generateQr' },
        { method: 'GET', path: '/api/admin/send-email/{orderId}/{nameFile}', action: 'sendPdfQuote' },
        { method: 'GET', path: '/api/admin/generate-order-pdf/{id}', action: 'generatePdfQuote' },
        { method: 'GET', path: '/api/admin/invoices', action: 'index' },
        { method: 'DELETE', path: '/api/admin/invoice/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/invoices/bulk-delete', action: 'bulkDelete' },
        { method: 'GET', path: '/api/admin/get-invoice/{id}', action: 'getInvoice' },
        { method: 'POST', path: '/api/admin/update-invoice-status', action: 'updateInvoiceStatus' },
        { method: 'GET', path: '/api/admin/get-pdf-receipt/{id}', action: 'returnReceiptPdf' },
        { method: 'POST', path: '/api/admin/generate-receipt-pdf/{id}', action: 'generateReceiptPdf' },
        { method: 'DELETE', path: '/api/admin/quickbooks/delete-invoice', action: 'deleteInvoice' },
        { method: 'POST', path: '/api/admin/quickbooks/update-invoice-status', action: 'updateQuickBooksInvoiceStatus' },
        { method: 'GET', path: '/api/admin/quickbooks/invoices/payments/{id}', action: 'getInvoicePayments' },
        { method: 'POST', path: '/api/admin/quickbooks/invoices/{id}/sync-payments', action: 'syncQuickBooksPaymentsToReceipts' },
        { method: 'POST', path: '/api/admin/invoice/process-partial-payment', action: 'processPartialPayment' },
        { method: 'GET', path: '/api/admin/get-temp-invoice-items', action: 'getItems (NewInvoice)' },
        { method: 'POST', path: '/api/admin/add-temp-invoice-item', action: 'addItem' },
        { method: 'POST', path: '/api/admin/edit-temp-invoice-item', action: 'editItem' },
        { method: 'DELETE', path: '/api/admin/delete-temp-invoice-item/{id}', action: 'deleteItem' },
        { method: 'POST', path: '/api/admin/process-invoice', action: 'processInvoice' },
        { method: 'POST', path: '/api/admin/generate-invoice-pdf/{id}', action: 'generateInvoicePdf' },
        { method: 'GET', path: '/api/admin/send-invoice-pdf/{id}', action: 'sendPdfInvoice' },
        { method: 'GET', path: '/api/admin/quote-requests', action: 'index' },
        { method: 'GET', path: '/api/admin/quote-request/{id}', action: 'show' },
        { method: 'DELETE', path: '/api/admin/quote-request/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/quote-requests/bulk-delete', action: 'bulkDelete' },
        { method: 'GET', path: '/api/admin/folder-manager', action: 'index' },
        { method: 'POST', path: '/api/admin/folder-manager', action: 'store' },
        { method: 'GET', path: '/api/admin/folder-manager/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/folder-manager/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/folder-manager/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/files-manager', action: 'index' },
        { method: 'POST', path: '/api/admin/files-manager', action: 'store' },
        { method: 'DELETE', path: '/api/admin/file-manager/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/chat/get-messages/{id}', action: 'getMessages' },
        { method: 'GET', path: '/api/admin/chat/group/{groupId}/messages', action: 'getGroupMessages' },
        { method: 'POST', path: '/api/admin/chat/send-message', action: 'sendMessage' },
        { method: 'PUT', path: '/api/admin/chat/message/{id}/edit', action: 'editMessage' },
        { method: 'DELETE', path: '/api/admin/chat/message/{id}', action: 'deleteMessage' },
        { method: 'GET', path: '/api/admin/chat/workstation/{workstationId}/users', action: 'getUsersByWorkstation' },
        { method: 'GET', path: '/api/admin/chat/users', action: 'getAllUsers' },
        { method: 'GET', path: '/api/admin/chat/workstations-groups', action: 'getUsersGroupedByWorkstation' },
        { method: 'POST', path: '/api/admin/reports/send', action: 'sendReport' },
        { method: 'GET', path: '/api/admin/chat/groups', action: 'index' },
        { method: 'POST', path: '/api/admin/chat/groups', action: 'store' },
        { method: 'GET', path: '/api/admin/chat/groups/{id}', action: 'show' },
        { method: 'PUT', path: '/api/admin/chat/groups/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/chat/groups/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/chat/groups/{id}/members', action: 'getMembers' },
        { method: 'POST', path: '/api/admin/chat/groups/{id}/members', action: 'addMembers' },
        { method: 'DELETE', path: '/api/admin/chat/groups/{groupId}/members/{personId}', action: 'removeMember' },
        { method: 'PUT', path: '/api/admin/chat/groups/{groupId}/members/{personId}/role', action: 'updateMemberRole' },
        { method: 'POST', path: '/api/admin/chat/groups/{id}/toggle-mute', action: 'toggleMute' },
        { method: 'GET', path: '/api/admin/categories', action: 'index' },
        { method: 'GET', path: '/api/admin/categories/active/{workstationId}/{module}', action: 'getActiveCategories' },
        { method: 'POST', path: '/api/admin/category', action: 'store' },
        { method: 'POST', path: '/api/admin/category/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/category/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/transactions', action: 'index' },
        { method: 'POST', path: '/api/admin/transaction', action: 'store' },
        { method: 'POST', path: '/api/admin/transaction/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/transaction/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/transactions/bulk-delete', action: 'bulkDelete' },
        { method: 'GET', path: '/api/admin/notifications', action: 'getNotifications' },
        { method: 'GET', path: '/api/admin/all-notifications', action: 'getAllNotifications' },
        { method: 'GET', path: '/api/admin/notifications/unread-count', action: 'getUnreadCount' },
        { method: 'POST', path: '/api/admin/notifications', action: 'store' },
        { method: 'POST', path: '/api/admin/notification/mark-as-read', action: 'markAsRead' },
        { method: 'POST', path: '/api/admin/notifications/mark-all-as-read', action: 'markAllAsRead' },
        { method: 'DELETE', path: '/api/admin/notifications/{notification}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/production-calendar', action: 'index' },
        { method: 'POST', path: '/api/admin/production-calendar', action: 'store' },
        { method: 'PUT', path: '/api/admin/production-calendar/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/production-calendar/{id}', action: 'destroy' },
        { method: 'PUT', path: '/api/admin/production-calendar/update-date/{id}', action: 'updateDate' },
        { method: 'POST', path: '/api/admin/quickbooks/auth-url', action: 'getAuthUrl' },
        { method: 'DELETE', path: '/api/admin/quickbooks/disconnect', action: 'disconnect' },
        { method: 'POST', path: '/api/admin/example/send-number', action: 'testQuickbooksInvoice' },
        { method: 'GET', path: '/api/admin/quickbooks/payments/{paymentId}', action: 'getPayment' },
        { method: 'GET', path: '/api/admin/quickbooks/invoices', action: 'getInvoices' },
        { method: 'GET', path: '/api/admin/quickbooks/invoices/{invoiceId}', action: 'getInvoice' },
        { method: 'POST', path: '/api/admin/quickbooks/invoices/{invoiceId}/send', action: 'sendInvoice' },
        { method: 'GET', path: '/api/admin/profile', action: 'profile' },
        { method: 'GET', path: '/api/admin/notes/contact', action: 'index' },
        { method: 'POST', path: '/api/admin/note/contact', action: 'store' },
        { method: 'PUT', path: '/api/admin/note/contact/{id}', action: 'update' },
        { method: 'GET', path: '/api/admin/notes', action: 'index (GeneralNotes)' },
        { method: 'POST', path: '/api/admin/new-note', action: 'store' },
        { method: 'PUT', path: '/api/admin/update-note/{id}', action: 'update' },
        { method: 'POST', path: '/api/admin/save-general-file', action: 'store' },
        { method: 'DELETE', path: '/api/admin/delete-general-file/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/tasks', action: 'index' },
        { method: 'GET', path: '/api/admin/task/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/task', action: 'store' },
        { method: 'PUT', path: '/api/admin/task/{id}', action: 'update' },
        { method: 'PUT', path: '/api/admin/task/{id}/complete', action: 'complete' },
        { method: 'DELETE', path: '/api/admin/task/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/tasks/bulk-delete', action: 'bulkDelete' },
        { method: 'GET', path: '/api/admin/leads-center', action: 'index' },
        { method: 'GET', path: '/api/admin/lead-categories', action: 'getLeadCategories' },
        { method: 'PUT', path: '/api/admin/update-lead-category', action: 'updateLeadCategory' },
        { method: 'PUT', path: '/api/admin/update-category', action: 'updateCategory' },
        { method: 'PUT', path: '/api/admin/update-source', action: 'updateSource' },
        { method: 'POST', path: '/api/admin/save-stage', action: 'saveStage' },
        { method: 'DELETE', path: '/api/admin/delete-stage/{id}', action: 'deleteStage' },
        { method: 'PUT', path: '/api/admin/update-stage/{id}', action: 'updateStage' },
        { method: 'POST', path: '/api/admin/update-project-manager-assign', action: 'updateProjectManagerAssign' },
        { method: 'POST', path: '/api/admin/save-fb-session', action: 'saveFbSession' },
        { method: 'GET', path: '/api/admin/check-fb-session', action: 'checkFbSession' },
        { method: 'GET', path: '/api/admin/sidebar-modules', action: 'getUserPermisions' },
        { method: 'GET', path: '/api/admin/person-documents/{id}', action: 'getPersonDocuments' },
        { method: 'GET', path: '/api/admin/work-orders', action: 'index' },
        { method: 'POST', path: '/api/admin/work-order', action: 'store' },
        { method: 'GET', path: '/api/admin/work-order/{id}', action: 'show' },
        { method: 'PUT', path: '/api/admin/work-order/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/work-order/{id}', action: 'destroy' },
        { method: 'GET', path: '/api/admin/get-admins-to-assign-work-order', action: 'getAdmins' },
        { method: 'POST', path: '/api/admin/update-assign-work-order', action: 'updatePersonAdminAssigned' },
        { method: 'POST', path: '/api/admin/person-work-order/{id}', action: 'deletePersonAssign' },
        { method: 'POST', path: '/api/admin/take-work-order', action: 'takeWorkOrder' },
        { method: 'POST', path: '/api/admin/update-status-work-order', action: 'updateWorkStatus' },
        { method: 'GET', path: '/api/admin/work-order-team/{workOrderId}', action: 'getWorkOrderTeam' },
        { method: 'POST', path: '/api/admin/assign-user-to-work-order', action: 'assignUserToWorkOrder' },
        { method: 'POST', path: '/api/admin/work-order-team/set-leader', action: 'setWorkOrderTeamLeader' },
        { method: 'GET', path: '/api/admin/work-order-notes', action: 'index' },
        { method: 'POST', path: '/api/admin/work-order-note', action: 'store' },
        { method: 'PUT', path: '/api/admin/work-order-note/{id}', action: 'update' },
        { method: 'DELETE', path: '/api/admin/work-order-note/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/work-order/files', action: 'saveWorkOrderFiles' },
        { method: 'GET', path: '/api/admin/work-order/files/{workOrderId}', action: 'getWorkOrderFiles' },
        { method: 'DELETE', path: '/api/admin/work-order/files/{id}', action: 'deleteWorkOrderFile' },
        { method: 'POST', path: '/api/admin/person/media', action: 'savePersonMedia' },
        { method: 'GET', path: '/api/admin/person/media/{personId}', action: 'getPersonMedia' },
        { method: 'DELETE', path: '/api/admin/person/media/{id}', action: 'deletePersonMedia' },
        { method: 'GET', path: '/api/admin/time-entries', action: 'index' },
        { method: 'POST', path: '/api/admin/time-entries/start', action: 'start' },
        { method: 'POST', path: '/api/admin/time-entries/stop', action: 'stop' },
        { method: 'GET', path: '/api/admin/time-entries/work-orders', action: 'workOrders' },
        { method: 'GET', path: '/api/admin/time-entries/orders', action: 'orders' },
        { method: 'POST', path: '/api/admin/time-entries/{id}/breaks/start', action: 'startBreak' },
        { method: 'POST', path: '/api/admin/time-entries/{id}/breaks/end', action: 'endBreak' },
        { method: 'POST', path: '/api/admin/time-entries/{id}/finish', action: 'finish' },
        { method: 'DELETE', path: '/api/admin/time-entries/{id}', action: 'destroy' },
        { method: 'POST', path: '/api/admin/time-entries', action: 'store' },
        { method: 'PUT', path: '/api/admin/time-entries/{id}', action: 'update' },
        { method: 'GET', path: '/api/admin/plans', action: 'index' },
        { method: 'GET', path: '/api/admin/plan-subscriptions', action: 'planSubscriptions' },
        { method: 'POST', path: '/api/admin/pay-plan-subscription', action: 'subscribeToPlan' },
        { method: 'GET', path: '/api/admin/get-subscription/{id}', action: 'getUserSubscription' },
        { method: 'POST', path: '/api/admin/new-subscription', action: 'newSubscription' },
        { method: 'PUT', path: '/api/admin/update-subscription/{id}', action: 'updateSubscription' },
        { method: 'DELETE', path: '/api/admin/delete-subscription/{id}', action: 'deleteSubscription' },
        { method: 'POST', path: '/api/admin/company', action: 'store' },
        { method: 'PUT', path: '/api/admin/company/{id}', action: 'update' },
        { method: 'GET', path: '/api/admin/companies', action: 'getAllCompanies' },
        { method: 'GET', path: '/api/admin/company-locations', action: 'getCompanyLocations' },
        { method: 'POST', path: '/api/admin/company-location', action: 'saveLocation' },
        { method: 'PUT', path: '/api/admin/company-location/{id}', action: 'updateLocation' },
        { method: 'DELETE', path: '/api/admin/company-location/{id}', action: 'deleteLocation' },
        { method: 'POST', path: '/api/admin/companies-contact', action: 'assignCompanyToContact' },
        { method: 'GET', path: '/api/admin/companies-contact', action: 'getCompaniesContact (Company)' },
        { method: 'POST', path: '/api/admin/terms-acceptance', action: 'acceptTerms' },
        { method: 'GET', path: '/api/admin/terms-acceptance/person/{personId}', action: 'getPersonTermsHistory' },
        { method: 'POST', path: '/api/admin/terms-acceptance/check/{personId}', action: 'hasAcceptedCurrentTerms' },
        { method: 'GET', path: '/api/admin/header-data', action: 'getHeaderData' },
        { method: 'GET', path: '/api/admin/validate-integrations', action: 'validateIntegrations' },
        { method: 'POST', path: '/api/admin/proposals', action: 'store (AdminProposal)' },
        { method: 'GET', path: '/api/admin/proposals/{id}', action: 'show' },
        { method: 'POST', path: '/api/admin/delete-files', action: 'deleteFiles' },
        { method: 'GET', path: '/api/admin/sms-call/messages', action: 'listSms (Sms)' },
        { method: 'GET', path: '/api/admin/sms-call/messages/{sid}', action: 'getSms (Sms)' },
        { method: 'POST', path: '/api/admin/sms-call/send-message', action: 'sendSms (Sms)' },
        { method: 'POST', path: '/api/admin/calls/make', action: 'makeCall (Call)' },
        { method: 'GET', path: '/api/admin/calls/list', action: 'listCalls (Call)' },
        { method: 'POST', path: '/api/admin/calls/token', action: 'getAccessToken (Call)' },
        { method: 'DELETE', path: '/api/admin/calls/hang-up/{callSid}', action: 'hangUp (Call)' },
        { method: 'GET', path: '/api/admin/calls/status/{callSid}', action: 'getStatus (Call)' },
        { method: 'GET', path: '/api/admin/phone-numbers/list', action: 'listNumbers (PhoneNumber)' },
        { method: 'GET', path: '/api/admin/phone-numbers/available', action: 'availableNumbers (PhoneNumber)' },
        { method: 'POST', path: '/api/admin/ia-chat-async', action: 'chatAsync' },
        { method: 'GET', path: '/api/admin/get-response', action: 'getResponse' },
        { method: 'GET', path: '/api/admin/integrations', action: 'index' },
        { method: 'POST', path: '/api/admin/integrations/gmail/disconnect', action: 'disconnectGmail' },
        { method: 'GET', path: '/api/admin/integrations/gmail/status/{workstationId}', action: 'checkStatus' },
        { method: 'GET', path: '/api/admin/integrations/ghl/company-id', action: 'getGHLCompanyId' },
        { method: 'GET', path: '/api/admin/integrations/ghl/companies', action: 'getGHLCompanies' },
        { method: 'GET', path: '/api/admin/email-system-status', action: 'closure (admin middleware)' }
      ]
    },
    {
      id: 'client-endpoints',
      title: 'Client (prefijo /api/client)',
      badge: 'public',
      routes: [
        { method: 'POST', path: '/api/client/quote', action: 'ContactMessageController@store' },
        { method: 'POST', path: '/api/client/confirm-quote/{id}', action: 'confirmQuote' },
        { method: 'POST', path: '/api/client/order-token', action: 'getOrderByToken' },
        { method: 'POST', path: '/api/client/process-order/{id}', action: 'processOrderByShoppingCart' },
        { method: 'POST', path: '/api/client/save-contact', action: 'saveNewContact' },
        { method: 'POST', path: '/api/client/invoice-token', action: 'getInvoiceByToken' },
        { method: 'POST', path: '/api/client/invoice-pay-token', action: 'getInvoicePayByToken' },
        { method: 'GET', path: '/api/client/invoice/{user_id}', action: 'invoice' },
        { method: 'POST', path: '/api/client/fetchclients', action: 'fetchclients' },
        { method: 'GET', path: '/api/client/allorders', action: 'allorders' },
        { method: 'GET', path: '/api/client/archived-orders', action: 'getArchivedOrders' },
        { method: 'GET', path: '/api/client/contact-name', action: 'getContactName' },
        { method: 'POST', path: '/api/client/confirm-advances', action: 'confirmAdvances' },
        { method: 'POST', path: '/api/client/confirm-proposal', action: 'confirmProposal' },
        { method: 'GET', path: '/api/client/footer-worstations', action: 'getWorkstations' },
        { method: 'GET', path: '/api/client/manager-contact/{lastname}', action: 'show' },
        { method: 'POST', path: '/api/client/register-back-contact', action: 'store (ManagerContact)' },
        { method: 'GET', path: '/api/client/facebook/webhook', action: 'FacebookWebhookController@verify' },
        { method: 'POST', path: '/api/client/facebook/webhook', action: 'receiveLead' },
        { method: 'GET', path: '/api/client/exchange-fb-token/{shortToken}', action: 'exchangeFbToken' },
        { method: 'GET', path: '/api/client/refresh-fb-token/{facebookId}', action: 'refreshFbToken' },
        { method: 'POST', path: '/api/client/facebook/save-page-token', action: 'savePageToken' },
        { method: 'GET', path: '/api/client/test-console', action: 'testConsoleFunction' }
      ]
    },
    {
      id: 'public-endpoints',
      title: 'Públicas (throttle:public)',
      badge: 'public',
      routes: [
        { method: 'GET', path: '/api/health', action: 'closure — health check' },
        { method: 'GET', path: '/api/user', action: 'closure — requiere auth:sanctum' },
        { method: 'POST', path: '/api/admin/quickbooks/connect', action: 'connectQuickBooks' },
        { method: 'GET', path: '/api/admin/quickbooks/connect', action: 'connectQuickBooksDirect' },
        { method: 'POST', path: '/api/login', action: 'login (throttle:auth)' },
        { method: 'POST', path: '/api/register', action: 'register (throttle:auth)' },
        { method: 'GET', path: '/api/admin/header-data', action: 'getHeaderData' },
        { method: 'POST', path: '/api/forgot-password', action: 'forgotPassword' },
        { method: 'POST', path: '/api/reset-password', action: 'resetPassword' },
        { method: 'POST', path: '/api/cancel-reset-password', action: 'cancelResetPassword' },
        { method: 'GET', path: '/api/admin/image/{image}', action: 'viewImageProfile' },
        { method: 'GET', path: '/api/admin/product/images/image/{id}', action: 'getImage' },
        { method: 'GET', path: '/api/image/{image}', action: 'viewRandomImage' },
        { method: 'GET', path: '/api/admin/order/files/{file}', action: 'viewOrderImages' },
        { method: 'GET', path: '/api/admin/order-comment/file/{fileName}', action: 'viewOrderCommentFile' },
        { method: 'GET', path: '/api/admin/order/file/{proposal}', action: 'viewOrderFile' },
        { method: 'GET', path: '/api/order/qr/{qr}', action: 'viewOrderQr' },
        { method: 'GET', path: '/api/admin/proposal/qr/{qr}', action: 'viewProposalQr' },
        { method: 'GET', path: '/api/admin/contact/qr/{qr}', action: 'viewContactQr' },
        { method: 'GET', path: '/api/admin/quote-requests/file/{file}', action: 'viewFile' },
        { method: 'GET', path: '/api/work-order/file/{file}', action: 'getWorkOrderImage' },
        { method: 'GET', path: '/api/work-order/qr/{token}', action: 'getWorkOrderQr' },
        { method: 'GET', path: '/api/work-order/qr-d/{token}', action: 'getWorkOrderQrD' },
        { method: 'GET', path: '/api/admin/work-order/media/{file}', action: 'viewWorkOrderImages' },
        { method: 'GET', path: '/api/admin/person/media/file/{file}', action: 'viewPersonMediaFile' },
        { method: 'GET', path: '/api/textures/{image}', action: 'getImage (Inventory)' },
        { method: 'GET', path: '/api/texture/{image}', action: 'getTexture' },
        { method: 'GET', path: '/api/workstation/logo/{image}', action: 'viewLogoWorkstation' },
        { method: 'GET', path: '/api/workstations/activeToLogin', action: 'getActiveWorkstationToLogin' },
        { method: 'POST', path: '/api/sms-call/save-received-sms', action: 'forwardToMicroservice (Sms)' },
        { method: 'GET', path: '/api/sms-call/file/{filename}', action: 'viewFile (Sms)' },
        { method: 'GET', path: '/api/ai-chat/file/{filename}', action: 'viewFile (AiChat)' },
        { method: 'GET', path: '/api/chat/file/{filename}', action: 'viewFile (Chat)' },
        { method: 'GET', path: '/api/admin/terms-acceptance/pdf/{personId}', action: 'downloadSignedPdf' },
        { method: 'GET', path: '/api/admin/role-text/pdf/{roleId}/{personId}', action: 'downloadRoleTextPdf' },
        { method: 'GET', path: '/api/user/qr/{userId}', action: 'getUserQr' },
        { method: 'GET', path: '/api/user/qr-d/{userId}', action: 'getUserQrD' }
      ]
    },
    {
      id: 'webhooks',
      title: 'Webhooks (throttle:webhooks)',
      badge: 'webhook',
      routes: [
        { method: 'POST', path: '/api/webhooks/quickbooks/payments', action: 'handlePaymentWebhook' },
        { method: 'POST', path: '/api/twilio/get-message-received', action: 'messageReceivedWebhook' },
        { method: 'POST', path: '/api/ghl/webhook', action: 'handleWebhook' },
        { method: 'POST', path: '/api/ghl/webhook/opportunity', action: 'handleWebhookOpportunity' }
      ]
    }
  ]
};
